New log file opened at Mon Mar 02 19:21:06 CET 2015 by 5380@User-PC
Taking next connection to: 50929
New client attempting to connect on port: 50930-50929
  Address = /192.168.1.36:50929
This client on port 50930 has uuid 991f23d0-7379-4b88-a93f-6431cd652a01 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-991f23d0-7379-4b88-a93f-6431cd652a01
Taking next connection to: 50929
New client attempting to connect on port: 50932-50929
  Address = /192.168.1.36:50929
Handshake exception on socket: 50932
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 50929
New client attempting to connect on port: 50933-50929
  Address = /192.168.1.36:50929
This client on port 50933 has uuid c375c7f4-e952-40f1-9e5a-4ed08c138cb3 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-c375c7f4-e952-40f1-9e5a-4ed08c138cb3
Taking next connection to: 50929
New client attempting to connect on port: 50946-50929
  Address = /192.168.1.36:50929
Handshake exception on socket: 50946
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 50929
New client attempting to connect on port: 50947-50929
  Address = /192.168.1.36:50929
This client on port 50947 has uuid 6823fb97-d015-47e9-9a63-0a8a12784694 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-6823fb97-d015-47e9-9a63-0a8a12784694
Taking next connection to: 50929
Checking to see if clients are empty...
No non-daemon clients connected after 3 min. Shutting down.
Server socket thread exiting.
0 clients open, will close them...
All client sockets have been closed.
Closing the 5380@User-PC logs at Mon Mar 02 19:26:52 CET 2015, goodbye.
